- .eslintrc.js
- .gitignore
- package.json
- src/components/NavBar.tsx
- yarn.lock
Added magic eslint comments until #2 gets resolved :) 
Related to #2
> chore: linter errors

- src/auth/authActions.ts
- src/auth/authReducer.ts
- src/auth/authSagas.ts
- src/components/NavBar.tsx
- src/locale/de.json
- src/locale/en.json
- src/utils/api.ts
Added logout and "unselect patient" buttons for authenticated users.
Fixes #2
> add logout and unselect patient buttons

- src/index.tsx
> add console log message 🥚

- .github/workflows/test.yml
- README.md
Added code coverage reporting with [codecov](https://codecov.io/)
> code coverage

- package.json
- src/__mocks__/axios.js
- src/auth/__tests__/AuthLayout.test.tsx
- src/auth/__tests__/authReducer.test.ts
- src/auth/__tests__/authSagas.test.ts
- src/auth/authReducer.ts
- src/auth/pages/Login.tsx
- src/questionnaires/__tests__/questionnairesReducer.test.ts
- src/questionnaires/__tests__/questionnairesSagas.test.ts
- src/questionnaires/questionnairesActions.ts
- src/questionnaires/questionnairesReducer.ts
- src/questionnaires/questionnairesSagas.ts
- src/questionnaires/testUtils.ts
- yarn.lock
Added simple tests for redux reducers and sagas.
> sagas tests

- public/_redirects
> chore: swap domains

- src/questionnaires/components/Field.tsx
- src/utils/constants.ts
- yarn.lock
Download the questionnaire files without logging in to backend.
> questionnaire file downloads

- .github/workflows/test.yml
- .gitignore
- cypress/e2e/nutri.js
- cypress/support/commands.js
- src/auth/pages/Login.tsx
more work for our little 🤖 
Added a simple login test.
> simple login e2e test

- package.json
- src/auth/__tests__/ChangePassword.test.tsx
- src/auth/__tests__/ForgotPassword.test.tsx
- src/auth/__tests__/Login.test.tsx
- src/auth/__tests__/ResetPassword.test.tsx
- src/auth/__tests__/SelectPatient.test.tsx
- src/auth/authReducer.ts
- src/auth/pages/ChangePassword.tsx
- src/auth/pages/ForgotPassword.tsx
- src/auth/pages/ResetPassword.tsx
- src/auth/useAutoLogin.ts
- src/dashboard/Dashboard.tsx
- src/dashboard/trackingOverview/components/TrackingOverviewHeader.tsx
- src/setupTests.js
- yarn.lock
More integration tests for the auth pages. It should cover what isn't covered in the e2e cypress tests.
> auth pages tests

- package.json
> chore: switch staging proxy

- package.json
- scripts/deploy.sh
Added a deploy script to run before the build step.
> chore: add deploy script for EU

- public/_headers
Add basic security headers to prevent [clickjacking](https://en.wikipedia.org/wiki/Clickjacking), [content sniffing](https://en.wikipedia.org/wiki/Content_sniffing) and XSS.
> chore: add basic security headers

- src/dashboard/trackingOverview/__tests__/FoodItemChips.test.tsx
> fix: randomly failing test

- src/chat/__tests__/Chat.test.tsx
- src/chat/__tests__/ChatDetails.test.tsx
- src/chat/__tests__/ChatHeader.test.tsx
- src/chat/__tests__/ChatMessagesList.test.tsx
- src/chat/__tests__/Inbox.test.tsx
- src/chat/__tests__/InboxSidebar.test.tsx
- src/chat/__tests__/InputToolbar.test.tsx
- src/chat/__tests__/Message.test.tsx
- src/chat/components/InputToolbar.tsx
- src/chat/components/Message.tsx
- src/chat/helpers.ts
- src/chat/pages/Inbox.tsx
- src/chat/redux/chatReducer.ts
- src/locale/en.json
- src/setupProxy.js
- src/utils/test-helpers.js
**Does this PR introduces a breaking change?**
> Chat tests

- src/chat/components/cards/HealthCard.tsx
Displaying diagnosis from backend in Health Card 🙂
> Display diagnosis in Health Card

- src/chat/__tests__/MessageDivider.test.tsx
- src/chat/components/Chat.tsx
- src/chat/components/ChatMessagesList.tsx
- src/chat/components/MessageDivider.tsx
- src/chat/components/cards/Details.tsx
- src/chat/redux/chatReducer.ts
Adding a message divider between different days
> Adding chat message divider. Also calculate last heard from.

- cypress/e2e/dashboard.js
- src/chat/components/ChatMessagesList.tsx
- src/chat/components/cards/UserInformation.tsx
- src/chat/redux/chatReducer.ts
- src/chat/redux/utils.ts
- src/components/IsPatientWrapper.tsx
- src/dashboard/Dashboard.tsx
- src/dashboard/__tests__/Dashboard.test.tsx
Fixing Message Divider Logic.
Restoring export/token logic and test unit & e2e.
Calculating and displaying the last contact.
> Fixing Message Divider logic. Restoring export/token functionality. 

- src/chat/components/inboxSidebar/Conversations.tsx
- src/chat/components/inboxSidebar/InboxSidebar.tsx
> Conversations list - update

- src/chat/__tests__/cards/CardBasicList.test.tsx
- src/chat/__tests__/cards/CardHeader.test.tsx
- src/chat/__tests__/cards/ChatDetails.test.tsx
- src/chat/__tests__/cards/Details.test.tsx
- src/chat/__tests__/cards/HealthCard.test.tsx
- src/chat/__tests__/cards/NotesInput.test.tsx
- src/chat/__tests__/cards/NotesList.test.tsx
- src/chat/__tests__/cards/UserInformation.test.tsx
- src/chat/__tests__/chat/Chat.test.tsx
- src/chat/__tests__/chat/ChatMessagesList.test.tsx
- src/chat/__tests__/chat/InputToolbar.test.tsx
- src/chat/__tests__/chat/InputToolbarTab.test.tsx
- src/chat/__tests__/chat/Message.test.tsx
- src/chat/__tests__/chat/MessageDivider.test.tsx
- src/chat/__tests__/chatHeader/AssignTeammate.test.tsx
- src/chat/__tests__/chatHeader/ChatHeader.test.tsx
- src/chat/__tests__/chatHeader/ChatHeaderLabel.test.tsx
- src/chat/__tests__/chatHeader/ChatHeaderLeftBox.test.tsx
- src/chat/__tests__/chatHeader/ChatHeaderRightBox.test.tsx
- src/chat/__tests__/chatRooms/ChatRoomItem.test.tsx
- src/chat/__tests__/chatRooms/ChatRooms.test.tsx
- src/chat/__tests__/chatRooms/ChatRoomsList.test.tsx
- src/chat/__tests__/inboxSidebar/InboxSidebar.test.tsx
- src/chat/components/inboxSidebar/Conversations.tsx
- src/chat/redux/chatReducer.ts
- src/chat/testHelpers.ts
New Tests and fixing dependency problem
> Testing new features

- src/chat/components/chat/Chat.tsx
- src/chat/components/chatRooms/ChatRooms.tsx
- src/chat/redux/chatActions.ts
- src/chat/redux/chatReducer.ts
- src/chat/redux/chatSagas.ts
- Fixing chat rooms pagination 
- Adding more types,
- Fixing get user data saga.
- Fixing problem with infinite load more 
https://user-images.githubusercontent.com/66030366/108987272-61528480-7693-11eb-9b5f-c2d9b27ce02a.mov
> Chat Improvements 

- .github/workflows/cla.yml
Shooting in the dark, trying to fix `cla.yml`.
> GitHub Actions

- package.json
- src/chat/KabelwerkContext.tsx
- src/chat/NotificationsContext.tsx
- src/chat/__tests__/chat/Message.test.tsx
- src/chat/components/chat/Message.tsx
- src/chat/components/chatHeader/ChatHeader.tsx
- src/chat/components/chatRooms/ChatRoomItem.tsx
- src/chat/components/chatRooms/ChatRooms.tsx
- src/chat/components/chatRooms/ChatRoomsList.tsx
- src/chat/components/inboxSidebar/Conversations.tsx
- src/chat/inboxes.ts
- src/chat/interfaces.ts
- src/chat/pages/Inbox.tsx
- src/components/NavBar.tsx
- src/components/__tests__/NavBar.test.tsx
- yarn.lock
- Upgraded the Kabelwerk SDK to [v0.2.0](https://github.com/kabelwerk/sdk-js/blob/master/CHANGELOG.md#020-2021-11-19).
- New chat feature: unread inbox items.
- New chat feature: desktop notifications on new message.
- Removed the now obsolete big green button from the navigation bar.
> Chat improvements

- package.json
- src/users/UserQrCode.tsx
- yarn.lock
**Description:**  This PR adds implementation to update the User QR Code screen with the scannable image.
> Update User QR Code screen with scannable image

- package.json
- src/users/UserQrCode.tsx
- yarn.lock
**Description:**  This PR merge implementation to update the User QR Code screen with the scannable image to master.
> Merge to master: Update User QR Code screen with scannable image (#96)

- src/analytics/AnalyticsHome.tsx
**Description:**  This PR adds an implementation to improve the search of user analytics in the Nutri Dashboard.
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-2054
> Improve search of user analytics in the Nutri Dashboard

- src/analytics/AnalyticsHome.tsx
This PR adds an implementation to show clinical trial codes if activated in the user analytics section.
**Does this PR introduces a breaking change?** No
> Show Clinical Trial Codes if Activated in User Analytics

- src/analytics/AnalyticsHome.tsx
This PR adds an implementation for the refactoring of module listing for the analytics dashboard search results.
**Does this PR introduces a breaking change?**
No
> Refactor modules listing for analytics dashboard search results

- src/epost/PrescriptionEpostService.tsx
- src/epost/epostUtils.ts
- src/home/HomeDashboard.tsx
- src/routes/index.ts
- src/utils/api.ts
[Jira Ticket](https://caracare.atlassian.net/browse/CCA-2218)
Adds a new page to the Dashboard with a form that allows a user to upload a PDF prescription and send it to the backend, where it will be forwarded to the Deutsch Post ePost service.
> Form to epost a prescription

- src/home/HomeDashboard.tsx
Adds a check to only show the prescription upload feature in the EU
> Add check to only show prescription upload in eu

- src/analytics/AnalyticsHome.tsx
- src/auth/__tests__/authReducer.test.ts
- src/auth/__tests__/authSagas.test.ts
- src/auth/authReducer.ts
- src/home/HomeDashboard.tsx
- src/users/RevokeAccess.tsx
This PR adds an implementation for the new permission settings for Care Panel.
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-2166
**Does this PR introduces a breaking change?**
No
> Care Panel: New permission settings

- src/epost/PrescriptionEpostService.tsx
- src/epost/Review.tsx
- src/epost/ReviewModal.tsx
- src/epost/Track.tsx
- src/epost/Upload.tsx
- src/epost/types.ts
- src/epost/useSearchPrescriptions.ts
- src/routes/index.ts
- src/theme/theme.ts
- src/utils/api.ts
[Jira ticket 2360](https://caracare.atlassian.net/browse/CCA-2360)
[Jira ticket 2579](https://caracare.atlassian.net/browse/CCA-2579)
- Adds a new Review page where draft letters can be approved or deleted
- Adds a new Tracking page where users can see the status of posted prescriptions
There were no designs, so the styling is very basic.
> Add tracking and review pages to ePost service

- src/epost/Review.tsx
Fixes a bug introduced after refactoring where I wasn't differentiating between deleting and posting and accidentally deleting everything - oops
> Fix review bug

- src/epost/Review.tsx
- src/epost/Upload.tsx
- src/epost/utils.ts
Refactors the handleSubmit function (which includes async logic) to use async/await. 
Also updates the times displayed in the Upload and Review sections to the Berlin timezone.
> Fix aysnc function

- cypress/e2e/dashboard.js
- src/analytics/AnalyticsHome.tsx
- src/analytics/UserInfo.tsx
- src/users/UserQrCode.tsx
**Description:**  This PR adds an implementation to improve user information on the analytics dashboard.
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-2707
> Care Panel: Improve user information on analytics dashboard

- src/epost/Track.tsx
Fixes a bug where the search query got reset if a user tried to get the next page of search results
> Fix the pagination of search results

- src/analytics/UserInfo.tsx
**Description:**  This PR adds an implementation to fix the questionnaire reset by updating the analytics dashboard.
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-2707
> Care Panel: Fix questionnaire reset by updating analytics dashboard

- src/epost/Review.tsx
- src/epost/ReviewModal.tsx
- src/epost/Track.tsx
- src/epost/Upload.tsx
- src/epost/types.ts
- src/utils/api.ts
**Description:**  This PR adds implementation for delayed ePost delivery with an option to cancel & send now.
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-2748
> Delayed ePost delivery with an option to cancel & send now

- src/analytics/UserInfo.tsx
- src/chat/contexts/KabelwerkContext.tsx
- src/epost/ReviewModal.tsx
- src/epost/Track.tsx
- src/routes/index.ts
**Description:**  This PR adds an implementation to display new data points in the Care Panel, remove chat dashboard forced authentication, and fix the delete draft text button.
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-2896
https://caracare.atlassian.net/browse/CCA-2904
> Add New Analytics Data Points and Fix Chat URL not opening and delete prescription draft button label

- src/analytics/UserInfo.tsx
**Description:**  This PR adds an implementation to display the account's active status on the Care Panel analytics dashboard.
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-2935
> Analytics Dashboard: Add account status field

- src/analytics/UserInfo.tsx
- src/utils/api.ts
**Description:**  This PR adds an implementation to add remove/add modules, update recipe collection, and mark questionnaires as completed in the analytics dashboard.
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-2993
> Analytics Dashboard: User Actions Feature

- src/analytics/AnalyticsHome.tsx
- src/analytics/UserInfo.tsx
**Description:**  This PR adds an implementation to auto-refresh the log page after submitting a user action.
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-3021
> Auto-Refresh the log page after submitting a user action

- src/analytics/AnalyticsHome.tsx
- src/analytics/userActionsList.json
**Description:**  This PR adds an implementation to add safety net functionality for user actions
**JIRA:** 
https://caracare.atlassian.net/browse/CCA-3020
> Analytics Dashboard: Add Safety net functionality for user actions
